---
- name: Изменение MOTD
  hosts: all
  become: true

  tasks:
    - name: Изменение  приветствия. Задание 2
      ansible.builtin.copy:
        dest: /etc/motd
        mode: '0644'
        content: |
          IP-адрес: {{ ansible_default_ipv4.address }}
          Hostname: {{ ansible_hostname }}
          Хорошего дня, системный администратор!
